In [1]:
import numpy as np
x = np.array([1,2,3,6,4,5])
y = x[::-1]
print(y)
print(np.flip(x,None))

[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [ ]:
arr1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print(np.resize(arr1,(1,9)))
a1 = arr1.ravel()
print(a1)
a1 = arr1.flatten()
print(a1)

[[1 2 3 2 4 5 1 2 3]]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print((arr1==arr2).all())
print(np.array_equal(arr1,arr2))

True
True


In [3]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def solve(x):
    values,cnts = np.unique(x,return_counts = True)
    index = np.argmax(cnts)
    el = values[index]
    indices = np.where(x==el)[0]
    print("Element: ",el)
    print("Indices: ",indices)

solve(x)
solve(y)

Element:  1
Indices:  [0 5 7 8 9]
Element:  1
Indices:  [0 1 2]


In [4]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
print("Sum: ",np.sum(gfg))
print("Row-wise sum:",np.sum(gfg,1))
print("Column-wise sum:",np.sum(gfg,0))

Sum:  45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [5]:
arr = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Diagonal sum: ", np.trace(arr))
print()
eigenvalues, eigenvectors = np.linalg.eig(arr)
print("Eigen values:", eigenvalues)
print("Eigen vectors:", eigenvectors)
print()
print("Inverse: ",np.linalg.inv(arr))
print()
print("Determinant: ",np.linalg.det(arr))

Diagonal sum:  176

Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant:  137180.0000000001


In [6]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("product:",np.dot(p,q))
print("product:",np.matmul(p,q))
print("covariance:",np.cov(p,q))
print()
p =  np.array([[1, 2], [2, 3], [4, 5]])
q =  np.array([[4, 5, 1], [6, 7, 2]])
print("product:",np.dot(p,q))
print("covariance:",np.cov(p,q.T))

product: [[16 19]
 [26 31]]
product: [[16 19]
 [26 31]]
covariance: [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

product: [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance: [[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


In [7]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product: ",np.inner(x,y))
print("Outer product: ",np.outer(x,y))

import itertools as it
print("Cartesian product: ",list(it.product(x,y)))

Inner product:  [[17 52]
 [13 62]]
Outer product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:  [(array([2, 3, 4]), array([1, 5, 0])), (array([2, 3, 4]), array([ 5, 10,  3])), (array([3, 2, 9]), array([1, 5, 0])), (array([3, 2, 9]), array([ 5, 10,  3]))]


In [12]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Element-wise absolute value:")
print(np.abs(array))
print()

print("Percentiles of flattened array (25th, 50th, 75th):")
print(np.percentile(array.flatten(), [25, 50, 75]))
print()

print("Percentiles for each column (25th, 50th, 75th):")
print(np.percentile(array, [25, 50, 75], axis=0))
print()

print("Percentiles for each row (25th, 50th, 75th):")
print(np.percentile(array, [25, 50, 75], axis=1))
print()

print("Mean of flattened array:", np.mean(array))
print("Median of flattened array:", np.median(array))
print("Standard Deviation of flattened array:", np.std(array))
print()

print("Mean of each column:", np.mean(array, axis=0))
print("Median of each column:", np.median(array, axis=0))
print("Standard Deviation of each column:", np.std(array, axis=0))
print()

print("Mean of each row:", np.mean(array, axis=1))
print("Median of each row:", np.median(array, axis=1))
print("Standard Deviation of each row:", np.std(array, axis=1))

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

Percentiles of flattened array (25th, 50th, 75th):
[-3.5 -0.5  2.5]

Percentiles for each column (25th, 50th, 75th):
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles for each row (25th, 50th, 75th):
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224

Mean of each column: [-1.5  1.5 -1.5]
Median of each column: [-1.5  1.5 -1.5]
Standard Deviation of each column: [2.5 3.5 4.5]

Mean of each row: [ 0.66666667 -1.66666667]
Median of each row: [ 1. -4.]
Standard Deviation of each row: [2.05480467 4.78423336]


In [13]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [16]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted = np.sort(array)
print("sorted array: ",sorted)
print("indices of sorted array: ", np.argsort(array))
print("4 smallest elements: ", sorted[:4])
print("5 largest elements: ", sorted[-5:])

sorted array:  [ 10  16  16  52  54  62 453]
indices of sorted array:  [0 3 4 1 5 2 6]
4 smallest elements:  [10 16 16 52]
5 largest elements:  [ 16  52  54  62 453]


In [22]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements: ",array[np.where(array == array.astype(int))])
print("Float elements: ",array[np.where(array == array.astype(float))])

[1. 2. 3. 2.]
[1.  1.2 2.2 2.  3.  2. ]


In [5]:
from PIL import Image
import os

def img_to_array(path, txt_path=None):
    img = Image.open(path)
    arr = np.array(img)

    if txt_path is None:
        base, _ = os.path.splitext(path)
        txt_path = base + '.txt'

    if arr.ndim == 2:
        # Grayscale image
        h, w = arr.shape
        header = f"# GRAYSCALE {h} {w}"
        np.savetxt(txt_path, arr, header=header, fmt='%d')
    elif arr.ndim == 3 and arr.shape[2] == 3:
        # RGB image
        h, w, c = arr.shape
        header = f"# RGB {h} {w} {c}"
        flat = arr.reshape(-1, 3)
        np.savetxt(txt_path, flat, header=header, fmt='%d')
    else:
        raise ValueError("Unsupported image format")

    print(f"Saved array data to {txt_path}")
    return arr


def load_img_array(txt_path):

    with open(txt_path, 'r') as f:
        header = f.readline().strip()
    parts = header.lstrip('# ').split()
    mode = parts[0]
    dims = list(map(int, parts[1:]))

    data = np.loadtxt(txt_path)

    if mode == 'GRAYSCALE':
        h, w = dims
        arr = data.reshape(h, w).astype(np.uint8)
    elif mode == 'RGB':
        h, w, c = dims
        arr = data.reshape(h, w, c).astype(np.uint8)
    else:
        raise ValueError("Unknown mode in header")

    return arr



img_arr = img_to_array(r"C:\Users\Parth\Downloads\front.jpg")
loaded = load_img_array('front.txt')
print(loaded)

Saved array data to C:\Users\Parth\Downloads\front.txt
[[[21 17 16]
  [21 17 16]
  [21 17 16]
  ...
  [16 12 11]
  [16 12 11]
  [16 12 11]]

 [[21 17 16]
  [21 17 16]
  [21 17 16]
  ...
  [16 12 11]
  [16 12 11]
  [16 12 11]]

 [[21 17 16]
  [21 17 16]
  [21 17 16]
  ...
  [16 12 11]
  [16 12 11]
  [16 12 11]]

 ...

 [[36 32 29]
  [35 31 28]
  [35 31 28]
  ...
  [14  7 14]
  [14  7 14]
  [14  7 14]]

 [[36 32 29]
  [35 31 28]
  [35 31 28]
  ...
  [14  7 14]
  [14  7 14]
  [14  7 14]]

 [[36 32 29]
  [35 31 28]
  [35 31 28]
  ...
  [14  7 14]
  [14  7 14]
  [14  7 14]]]
